# Site settings
title: Salih Erdem
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Salih Erdem
user_description: Merhabalar, Karabük Üniversitesi Elektrik Elektronik Mühendisliği mezunuyum. Gömülü sistem tasarımı, elektronik donanım ve yazılım tasarımı alanlarında çalışmaktayım. Kendimi; belirli bir tecrübeye ve iş disiplinine sahip, yeni hedefleri olan, başarıyı kovalayan biri olarak ifade edebilirim.
user_title: Electrical & Electronics Engineer
email: erdmsalih@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
